services:
  - type: web
    name: pretentious-blog
    env: ruby
    plan: free
    buildCommand: bundle install
    startCommand: ./bin/render-build.sh
    envVars:
      - key: RACK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pretentious-blog-db
          property: connectionString

databases:
  - name: pretentious-blog-db
    plan: free
    databaseName: blog_production
