services:
  - type: web
    name: my-blog
    env: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec rackup -E production -p $PORT # or puma
    envVars:
      - key: RACK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: my-blog-db # ← must match your Postgres service name
          property: connectionString # ← this injects the internal URL automatically

databases:
  - name: my-blog-db
    plan: free
    databaseName: blog_production # optional – defaults to something random
    user: rebeca # optional
